name: quwikpark_backend
description: A server-side application for the QuwikPark app.
version: 1.0.0

environment:
  environment:
  sdk: '>=3.0.0 <4.0.0'  // <-- This is the fix

dependencies:
  alfred: ^1.1.0  # <-- ADD THIS LINE

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0